# Generated by Django 4.1 on 2022-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resolucion_auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion_desc', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'resolucion auditoria',
                'verbose_name_plural': 'resolucion auditorias',
                'db_table': 'resolucion?auditoria',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
