# Generated by Django 4.1 on 2022-12-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0002_resolucion_auditoria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resolucion_auditoria',
            table='resolucion_auditoria',
        ),
    ]
