# Generated by Django 4.1 on 2022-09-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0003_alter_auditorias_diarias_dc_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorias_diarias',
            name='container_stat_cd',
            field=models.CharField(max_length=4),
        ),
    ]
