# Generated by Django 4.1 on 2022-12-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0003_alter_resolucion_auditoria_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucion_auditoria',
            name='resolucion_desc',
        ),
        migrations.AddField(
            model_name='resolucion_auditoria',
            name='obs_auditoria_cd',
            field=models.CharField(default='Ninguno', max_length=30),
        ),
    ]
