# Generated by Django 4.1 on 2022-11-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0003_alter_auditorias_diarias_resolucion_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorias_diarias',
            name='resolucion_cd',
            field=models.CharField(choices=[('Pendiente', '1'), ('En Progreso', '2'), ('Terminado', '3'), ('Cancelado', '4')], default='Pendiente', max_length=13),
        ),
    ]
