# Generated by Django 4.1 on 2022-11-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0004_alter_auditorias_diarias_resolucion_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorias_diarias',
            name='resolucion_cd',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=13),
        ),
        migrations.AlterField(
            model_name='auditorias_diarias',
            name='user',
            field=models.CharField(blank=True, default='No Asign', max_length=8, null=True, verbose_name='Auditor'),
        ),
    ]
