# Generated by Django 4.1 on 2022-12-01 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0004_remove_resolucion_auditoria_resolucion_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorias_diarias',
            name='obs_auditoria_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpbd.resolucion_auditoria'),
        ),
    ]
