# Generated by Django 4.1 on 2022-11-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0005_alter_auditorias_diarias_container_stat_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciones',
            name='create_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auditorias_diarias',
            name='user_supervisor_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Supervisor'),
        ),
    ]
