# Generated by Django 4.1 on 2022-12-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0005_alter_auditorias_diarias_obs_auditoria_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion_desc', models.CharField(default='Ninguno', max_length=30)),
                ('usuario', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'estado auditoria',
                'verbose_name_plural': 'estados auditorias',
                'db_table': 'estado_auditoria',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.AlterField(
            model_name='auditorias_diarias',
            name='resolucion_cd',
            field=models.CharField(choices=[('j0c0af6', 'j0c0af6'), ('v0j0af6', 'v0j0af6'), ('C0j0a56', 'C0j0a56'), ('Z0j0a30', 'Z0j0a30')], default='Pendiente', max_length=13),
        ),
    ]
