# Generated by Django 4.1 on 2022-11-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0006_asignaciones_create_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciones',
            name='container_stat_cd',
            field=models.IntegerField(default='15'),
        ),
        migrations.AlterField(
            model_name='asignaciones',
            name='create_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Creación Etiqueta'),
        ),
    ]
