# Generated by Django 4.1 on 2022-12-01 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0006_estado_auditoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorias_diarias',
            name='resolucion_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpbd.estado_auditoria'),
        ),
    ]
