# Generated by Django 4.1 on 2022-12-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpbd', '0007_alter_auditorias_diarias_resolucion_cd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado_auditoria',
            old_name='resolucion_desc',
            new_name='estado_desc',
        ),
    ]
